server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 可选：将 /api 请求直接反向代理到你的 FastAPI 服务
    location /api/ {
        proxy_pass http://159.195.158.129:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}